services:

  postgres:
    image: postgres:17

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: backend-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: backend_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: backend-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  user-service:
    build:
      context: ../services/user-service

    container_name: user-service

    ports:
      - "8000:8000"

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: backend_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  auth-service:
    build:
      context: ../services/auth-service

    container_name: auth-service

    ports:
      - "8001:8000"

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    depends_on:
      user-service:
        condition: service_started

  stats-api:
    build: ../services/stats-service
    container_name: stats-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin
    ports:
      - "8002:8000"
    depends_on:
      rabbitmq:
          condition: service_healthy

  stats-worker:
    build: ../services/stats-service
    container_name: stats-worker
    command: python app/consumer.py
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: admin

    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: